# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'get_latest_by': 'pk', 'ordering': ('-pk',)},
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
